Repository surfstudio/NodeKit, pull requests merged in 2018-08, with the labels that each got.

#31 Make request completion closure escaping
  CoreNetKit/Core/BaseServerRequest.swift
Labels: enhancement

#32 Добавил ROADMAP
  ROADMAP.md
Labels: question

#45 #33 fix leaks
  CoreNetKit/Kit/Pagination/BaseIteratableContext.swift
Labels: bug
